language: python
python:
    - "2.7"
install:
    - pip install -r dependencies.txt
    - pip install coveralls
script:
    - py.test Testing/test_tiles2gpkg.py --doctest-modules -v --cov Packaging --cov-report term-missing
after_success:
    - coverage run --source=Packaging Testing/test_tiles2gpkg.py
    - coverage report -m
    - coveralls --verbose
