language: python
python:
    - "2.7"
install:
    - pip install -r dependencies.txt
    - pip install coveralls
script:
    - py.test Testing/test_tiles2gpkg.py --doctest-modules -v --cov Packaging --cov-report term-missing
after_success:
    - coveralls
